In [2]:
import numpy as np
r1 = 11000
r2 = 22000
c = 4 * 10**(-6)
d = 0.025
w1 = 150
w2 = 300
dc = 0.0007
c0 = 10**(-7)
sc = 35*10*10**(-6)

In [3]:
Uxm = np.array([10,10,10,10,10,10, 5,5,5, 2])
Uym = np.array([5,5,5,5,5,5,5,5,5,2])
H = Uxm/r1/np.pi/d*w1
B = Uym/w2/np.pi/d**2*4*r2*c
Uxe = 20
Uye = np.array([2,2,2,5])
E = Uxe/dc
D = Uye/sc*c0
Ecorr = np.array([E, E*2, E*3, E*4])
Dcorr = np.array([D, D*2, D*3])
Hcorr = np.array([H, H*2, H*3, H*4])
Bcorr = np.array([B, B*2, B*3])
print(np.round(Hcorr, 2), "A/m")
print(np.round(Bcorr, 2), "мТл")
print(np.round(Ecorr, 2), "В/м")
print(np.round(Dcorr*10**3, 2), "мКл/м^2")

[[1.74 1.74 1.74 1.74 1.74 1.74 0.87 0.87 0.87 0.35]
 [3.47 3.47 3.47 3.47 3.47 3.47 1.74 1.74 1.74 0.69]
 [5.21 5.21 5.21 5.21 5.21 5.21 2.6  2.6  2.6  1.04]
 [6.94 6.94 6.94 6.94 6.94 6.94 3.47 3.47 3.47 1.39]] A/m
[[2.99 2.99 2.99 2.99 2.99 2.99 2.99 2.99 2.99 1.2 ]
 [5.98 5.98 5.98 5.98 5.98 5.98 5.98 5.98 5.98 2.39]
 [8.96 8.96 8.96 8.96 8.96 8.96 8.96 8.96 8.96 3.59]] мТл
[ 28571.43  57142.86  85714.29 114285.71] В/м
[[0.57 0.57 0.57 1.43]
 [1.14 1.14 1.14 2.86]
 [1.71 1.71 1.71 4.29]] мКл/м^2


In [30]:
s = np.array([[25.1, 1.2], [42.2, 1.4], [40.7, 1.2], [42.4, 1.3], [30.5, 1.2], [25, 1.2], [38, 1.5], [27.8, 1.2], [22, 1.4], [20.8, 1.2], [2.6, 1.3], [6.4, 1.9], [3.4, 1.3], [3.9, 3]])
scorr = np.array([])
for i in range(0,10):
    a = s[i][0]/s[i][1]*H[i]*B[i]*10**(-3)
    scorr = np.append(scorr, a)
for i in range(0, 4):
    a = s[i+10][0]/s[i+10][1]*E*D[i]
    print(a)
    scorr = np.append(scorr, a)
for i in scorr:
    print(f"Теплота, мДж {i*1000:.2f}")
for i in s:
    print(i[0]/i[1])

32.6530612244898
54.99462943071966
42.70015698587128
53.06122448979592
Теплота, мДж 108.51
Теплота, мДж 156.37
Теплота, мДж 175.95
Теплота, мДж 169.20
Теплота, мДж 131.85
Теплота, мДж 108.08
Теплота, мДж 65.71
Теплота, мДж 60.09
Теплота, мДж 40.76
Теплота, мДж 7.19
Теплота, мДж 32653.06
Теплота, мДж 54994.63
Теплота, мДж 42700.16
Теплота, мДж 53061.22
20.916666666666668
30.142857142857146
33.91666666666667
32.61538461538461
25.416666666666668
20.833333333333336
25.333333333333332
23.166666666666668
15.714285714285715
17.333333333333336
2.0
3.368421052631579
2.6153846153846154
1.3


In [13]:
Hc = np.array([3.2, 0.05])*0.35
Bn = np.array([1.1, 0.05])*1.2
print(np.round(Hc,3))
print(np.round(Bn,2))

[1.12  0.017]
[1.32 0.06]


In [24]:
Ec = np.array([0.15, 0.3, 0.35, 0.4, 0.05])/2*E
Dn = np.array([3.6, 3.4, 3.3, 2.4, 0.05])*D[0]*5/2
print(np.round(Ec/1000,1))
print(np.round(Dn*1000,2))

[2.1 4.3 5.  5.7 0.7]
[5.14 4.86 4.71 3.43 0.07]
